name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
      - name: Use nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b #v3.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn --network-concurrency 1
      - name: tests
        run: |
          yarn test
        env:
          CI: true
      - name: build
        run: yarn build
      - name: storybook build
        run: yarn build-storybook
